---
title: "Inicio"
---

<div class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Casos totales. Según información de la Secretaría de Salud</strong> <a href="#" class="alert-link"> 51,633  </a>
</div>

<div class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Muertes totales. Según información de la Secretaría de Salud</strong> <a href="#" class="alert-link">5,332     </a>
</div>


<div class="jumbotron">
  <p class="my-4">Este sitio, <a href="https://datos.gob.mx/busca/dataset/informacion-referente-a-casos-covid-19-en-mexico " target="_blank">con base en información pública</a>, reporta datos sobre las defunciones según: padecimientos, sexo, grupos de edad, etnia, estado de residencia y sector de salud. </p>
  <hr class="my-4">
  <p>La información del sitio se organiza conforme a las siguientes cuatro secciones, cada una con pestañas para la consulta de datos por grupo poblacional, estado o sector. Las cuatro secciones se pueden ingresar con los botones azules que se muestran a continuación o desde el menú <a href="https://hectornajera83.github.io/COVID19Mexico/Analisis.html" target="_blank">Análisis de datos</a>. </p>
</div>


> 1. Prevalencia cruda de muertes por COVID-19 por grupos de población y padecimientos <a href="https://hectornajera83.github.io/COVID19Mexico/COVID19_ws1.html" class="btn btn-info">Prevalencia cruda</a>

>> Las gráficas de esta sección se limitan a sistematizar un conjunto de las principales variables que se encuentran en la base de datos en <a href="https://datos.gob.mx/busca/dataset/informacion-referente-a-casos-covid-19-en-mexico " target="_blank">la dirección oficial de la Secretaría de Salud</a>. 

> 2. Prevalencia ajustada de muertes por COVID-19 por grupos de población y padecimientos <a href="https://hectornajera83.github.io/COVID19Mexico/COVID19_ws2.html" class="btn btn-info">Prevalencia ajustada</a>

>> La prevalencia ajustada informa la probabilidad de fallecer por una de las variables consideradas, manteniendo las demás constantes, por ejemplo, la estimación del efecto de la diabetes sobre la probabilidad de fallecer, es neto en la medida que se controla por el efecto de las otras variables consideradas en el modelo. Se responde así una pregunta frecuentemente formulada ¿Hasta qué punto la probabilidad de fallecer depende de la edad y no de alguna enfermedad? Lo que se presenta en este conjunto de gráficas es la dependencia de la probabilidad de morir de cada una de las variables consideradas.

> 3. Prevalencia ajustada de muertes por COVID-19 según características de la atención <a href="https://hectornajera83.github.io/COVID19Mexico/COVID19_ws3.html" class="btn btn-info">Análisis institucional</a>

>>  Este micrositio informa sobre la probabilidad de fallecer por uno de los factores condicionantes del sector salud y por estado, controlando el efecto de los demás; se cataloga como neto porque “elimina” el efecto de las otras fuentes que condicionan la probabilidad de fallecer por COVID-19.

> 4. Síntesis de los factores de riesgo <a href="https://hectornajera83.github.io/COVID19Mexico/resumen.html" class="btn btn-info">Factores de riesgo</a>

>> Muestra los factores que incementan o disminuyen el riesgo de fallecer por COVID-19. 

<div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4>Atención!</h4>
  <p>La información se actualiza diariamente <a href="https://datos.gob.mx/busca/dataset/informacion-referente-a-casos-covid-19-en-mexico " class="alert-link">Información pública</a>.</p>
</div>









