---
title: "Resumen factores de riesgo"
---

El siguiente cuadro muestra la relación de distintos factores demográficos, institucionales y de salud con el riesgo de muerte de COVID-19 en México. Los resultados de la columna *incremento* se obtuvieron de un modelo de regresión bayesiano descrito en la sección Notas.

* Incremento alto en riesgo: Existe cuando el factor en cuestión tiene signo positivo en el modelo y el intervalo de confianza creible no contiene cero al 95%.

* Reducción en riesgo: Existe cuando el factor en cuestión tiene signo negativo en el modelo y el intervalo de confianza creible no contiene cero al 95%.

* Sin evidencia de su efecto: El intervalo de confianza creible contiene cero. 

```{r echo=FALSE, warning=FALSE, message=FALSE}
load("Model.B")
library(kableExtra)

a<-as.data.frame(Model.B$fit)
a<-sapply(a, function(x) quantile(x, probs=c(.025,.5,.975)))
a<-t(a)
a[14:21,]<-a[14:21,]*-1
a<-exp(round(a,2))
a<-as.data.frame(a)

a$Factor<-c("Intercept","Tiempo atención","Tiempo atención 2", "Institución atención: Estatal","Institución atención: IMSS", "Institución atención: ISSSTE", "Institución atención: PEMEX", "Institución atención: PRIVADA", "Institución atención: SSA", "Institución atención: SEMAR", "Edad", "Edad 2", "Habla indígena", "Con Obesidad", "Con enfermedad cardiovascular", "Con enfermedad renal crónica", "Tabaquismo", "Con hipertensión", "Con inmunosupresores", "Asma", "Con diabetes", "Embarazo", "Sexo: Mujer",
            "Enfermó la última semana", "Enfermó hace dos semanas", "Enfermó hace tres semanas", "Linear")


a<-a[,2:4]
a<-a[c(-1,-3,-12,-20,-24,-25,-26,-27),]
a$Efecto<-c("Incrementa riesgo", "Incrementa riesgo (ref=otro)", "Incrementa riesgo (ref=otro)","Incrementa riesgo (ref=otro)", "Sin evidencia de efecto",
            "Reducción en riesgo (ref=otro)", "Incrementa riesgo (ref=otro)", "Reducción en riesgo (ref=otro)", 
            "Incrementa riesgo", "Incrementa riesgo", "Incrementa riesgo", "Sin evidencia de efecto", "Incrementa riesgo", "Sin evidencia de efecto", "Incrementa riesgo", "Incrementa riesgo", "Incrementa riesgo", "Sin evidencia de efecto", "Reducción riesgo (ref=Hombre)")

a<-a[,3:4]
rownames(a)<-NULL

kable(a) %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),  full_width = F, font_size = 14) %>%
  row_spec(c(2,7,9,10,11,13,15,16,17), bold = T, color = "white", background = "#F62217") %>%
  row_spec(c(1,3,4,7), bold = T, color = "white", background = "#FFC2B7") %>%
  row_spec(c(6,8,19), bold = T, color = "white", background = "#306754") %>%
  column_spec(1, width = "20em") %>%
  column_spec(2, width = "20em")
```

Referencia: 

1. Istituciones: La referencia son las instituciones con menor riesgo: SEMAR y Privado.

2. Enfermedades: La referencia es tener la enfermedad. 

